### ISSUE TITLE
User Registration (student)

### ISSUE THREAD

**Issue by LeviButcher** [studentsXbooks/studentsXbooks-app#5]
Sam goes to {domain} and is shown a Home page. The Page ask sam to register an account. Sam clicks to register an account and she is greeted with a Registration page with an email, username, and password input boxes telling her to enter a ‘edu’ email address. Sam enters in her student email, username, and password and hits submit. The site then sends her back to the Welcome screen with a pop up box saying ‘a confirmation email has been sent to {email}, please check your inbox’. Sam checks her inbox and see an email from {domain}. Sam clicks the confirmation link within the email and is sent to the {domain}. She can now see her username she entered earlier in the top navigation of the site. Also, a pop up box has appeared saying ‘Account successfully confirmed’.

Technical Requirements:
- Must use cookie based authentication

**Comment by jeremii** [comment]
Maybe we can take user stories a step further and present them as a checklist. It's like a cross between use case tables and user stories. @GandoraGalaxy could use them for acceptance testing too. We could use the comments to indicate the whether the issue is in implementation or verification phase, and hand it off to the tester with a casual @ tag.

Example:
- [ ] Sam goes to {domain} and is shown a Home page.
- [ ] The Page ask sam to register an account.
- [ ] Sam clicks to register an account and she is greeted with a Registration page with an email, username, and password input boxes telling her to enter a ‘edu’ email address.
- [ ] Sam enters in her student email, username, and password and hits submit.
- [ ] The site then sends her back to the Welcome screen with a pop up box saying ‘a confirmation email has been sent to {email}, please check your inbox’.
... etc.

I wonder what the industry thinks of this approach? Whatever's efficient perhaps? I couldn't find anything on Google.

**Comment by LeviButcher** [comment]
- [ ] Finish Registration test completely
- [ ] Refactor UI to new process
- [ ] Convert from SendGrid to vanilla .net core for email sending

**Comment by LeviButcher** [comment]
Pull request in by 9/30/2019

**Comment by LeviButcher** [comment]
- [ ] Add in all Login Tests, check the google doc
- [ ] EmailConfirm_NewUserValidToken_ReturnOkAndUserAccountConfirmIsTrueAndCookieReturned doesn't test everything it should, the cookie isn't tested for right now
  - [ ] discuss with me why we need all the extra assertions
- [ ] change api for registering "api/users/new" to "api/users/register"
    - [ ] check to make sure all other apis make sense
    - [ ] remove unnecessary apis if they are not needed for user story
- [ ] Login shouldn't use anything from MVC dotnet, aka the redirects and stuff but that should be taken care of when matching the tests.
- [ ] email Confirm page could have some loading state while calling the backend, discuss with me about it then implement.
